<?php

/**
 * @file
 * This module provides a number of custom blocks
 *
 * - header block for subject (taxonomy) page
 * - inline navigation block for subject (taxonomy) page
 * - roadmap block for subject (taxonomy) page (divided according to subject divisions vocabulary)
 * - header block for course (node) page
 * - "product variations" (public dates) for course (node) page
 * - testimonial block for course (node) page
 * - header block for team (node) page
 * - testimonial block for trainer (node) page
 * - inline navigation block for course (node) page
 * - generic title block which only contains the page title
 *
 */

/**
 * Implements hook_block_init
 */
function hc_blocks_init() {
  $path = drupal_get_path('module', 'hc_blocks');
  drupal_add_css($path . '/hc_blocks.css');
}

/**
 * Implements hook_block_info
 */
function hc_blocks_block_info() {
  $blocks = array();
  
  $blocks['catalog_subject_header'] = array(
    'info' => t('Catalog Subject Page Header'),
  );
  
  $blocks['catalog_subject_navigation'] = array(
    'info' => t('Catalog Subject Page Navigation'),
  );
  
  $blocks['catalog_subject_course_roadmap'] = array(
    'info' => t('Catalog Subject Page Course Roadmap'),
  );
  
  $blocks['course_header'] = array(
    'info' => t('Course Page Header'),
  );
  
  $blocks['course_public_dates'] = array(
    'info' => t('Course Public Dates'),
  );
  
  $blocks['course_testimonials'] = array(
    'info' => t('Course Testimonials'),
  );
  
  $blocks['team_header'] = array(
    'info' => t('Team Page Header'),
  );
  
  $blocks['trainer_testimonials'] = array(
    'info' => t('Trainer Testimonials'),
  );
  
  $blocks['book_a_course_navigation'] = array(
    'info' => t('Book a Course Page Navigation'),
  );
  
  $blocks['page_title'] = array(
    'info' => t('Page Title'),
  );

  
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function hc_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'catalog_subject_header':
      $block['content'] = _hc_blocks_block_catalog_subject_header_render();
      break;
    case 'catalog_subject_navigation':
      $block['subject'] = t('Navigation');
      $block['content'] = _hc_blocks_block_catalog_subject_navigation_render();
      break;
    case 'catalog_subject_course_roadmap':
      $block['subject'] = _hc_blocks_block_catalog_subject_course_roadmap_render_title();
      $block['content'] = _hc_blocks_block_catalog_subject_course_roadmap_render();
      break;
    case 'course_header':
      $block['content'] = _hc_blocks_block_course_header_render();
      break;
    case 'course_public_dates':
      $block['subject'] = _hc_blocks_block_course_public_dates_render_title();
      $block['content'] = _hc_blocks_block_course_public_dates_render();
      break;
    case 'course_testimonials':
      $block['subject'] = t('Course Testimonials');
      $block['content'] = _hc_blocks_block_course_testimonials_render();
      break;
    case 'team_header':
      $block['content'] = _hc_blocks_block_team_header_render();
      break;
    case 'trainer_testimonials':
      $block['subject'] = t('Trainer Testimonials');
      $block['content'] = _hc_blocks_block_trainer_testimonials_render();
      break;
    case 'book_a_course_navigation':
      $block['subject'] = t('Navigation');
      $block['content'] = _hc_blocks_block_book_a_course_navigation_render();
      break;
    case 'page_title':
      $block['content'] = _hc_blocks_block_page_title_render();
  }
  
  return $block;
}

/**
 * Helper function for rendering Catalog subject page header block
 */
function _hc_blocks_block_catalog_subject_header_render() {
  $block = array();
  
  if (is_numeric(arg(2))) {
    $tid = arg(2);
    $term_wrapper = entity_metadata_wrapper('taxonomy_term', $tid);
    $term_name = $term_wrapper->name->value();
    $term_description = $term_wrapper->description->value();
    $term_header_visual = $term_wrapper->field_catalog_header_visual->value();
    $header_visual_path = image_style_url('subject_header_default', $term_header_visual['uri']);
//    $header_visual_path = file_create_url($term_header_visual['uri']);
    $header_visual = theme('image', array('path' => $header_visual_path));

		$output = "<div class='image'>" . $header_visual . "</div>"
		  . "<div class='text'>"
		  . "<div class='title'>" . $term_name . "</div>"
		  . "<div class='description'>" . $term_description . "</div>"
		  . "</div>";

  } 
  
  $block['#markup'] = $output;
  
  return $block;
}


/**
 * Helper function for rendering Catalog subject page navigation block
 */
function _hc_blocks_block_catalog_subject_navigation_render() {
  $block = array();
  
  if (is_numeric(arg(2))) {
    $tid = arg(2);
    $term_wrapper = entity_metadata_wrapper('taxonomy_term', $tid);
    $term_name = $term_wrapper->name->value();
    $field_block = $term_wrapper->field_block->value();

    if (is_array($field_block)) {
      $items = array();
      $items[] = array('data' => '<p class="title">' . t('Have questions?<br />Click for an answer.') . '</p>');
      
      foreach ($field_block as $block_item) {
        $field_block_wrapper = entity_metadata_wrapper('field_collection_item', $block_item->item_id);
        $title = $field_block_wrapper->field_block_title->value();
        $items[] = array('data' => "<a href='#'>" . $title . "</a>", 'data-naventityid' => $block_item->item_id);
      }
      
      $items[] = array('data' => "<a href='#'>" . t('What is the @term_name course roadmap?', array('@term_name' => $term_name)) . "</a>");
    }

  } 
  $block['#markup'] = theme('item_list', array('items' => $items));
  
  return $block;
}

/**
 * Helper function for rendering Catalog subject page course roadmap title
 */
function _hc_blocks_block_catalog_subject_course_roadmap_render_title() {
  
  $title = "";
  if (is_numeric(arg(2))) {
    $tid = arg(2);
    $term_wrapper = entity_metadata_wrapper("taxonomy_term", $tid);
    $term_name = $term_wrapper->name->value();
    $title = t('What is the @title course roadmap?', array('@title' => $term_name));
  }
  
  return $title;
}

/**
 * Helper function for rendering Catalog subject page course roadmap
 */
function _hc_blocks_block_catalog_subject_course_roadmap_render() {
  $block = array();
  $subject_divisions = array();
  $items = array();
  
  if (is_numeric(arg(2))) {
    $tid = arg(2);
  }
  
  $result = db_query("SELECT * FROM {field_data_field_subject} s, {field_data_field_global_order} o WHERE s.field_subject_tid=:tid 
                      AND s.entity_id = o.entity_id AND o.bundle = 'subject_divisions' ORDER BY o.field_global_order_value ASC;", 
            array(':tid' => $tid));
  foreach ($result as $row) {
    // region check here
    $current_location = $_SESSION['user_location']['continent_code'];
    $subject_division_wrapper = entity_metadata_wrapper('taxonomy_term', $row->entity_id);
    $region_field = $subject_division_wrapper->field_global_region->value();
    if (in_array($current_location, $region_field)) {
      $subject_divisions[] = $row->entity_id; 
    }
  }
    

  
  // for subjects containing divisions
  if (count($subject_divisions)) {
	  foreach ($subject_divisions as $division_tid) {
	    $output_courses = "";
	    $items_course_nids = array();
	    // get basic info for this division
	    $division_term = entity_metadata_wrapper('taxonomy_term', $division_tid);
	    $division_title = $division_term->name->value();
	    $division_description = $division_term->description->value();
	    
	    // get courses belonging to this division
	    $result = db_query("SELECT * FROM {field_data_field_course_training_division} d, {field_data_field_global_order} o WHERE d.field_course_training_division_tid=:tid
	                        AND d.entity_id = o.entity_id ORDER BY o.field_global_order_value ASC;",
	              array(':tid' => $division_tid));
	              
	    // do region check
	    $current_location = $_SESSION['user_location']['continent_code'];
	    foreach ($result as $row) {
	      $entity_id = $row->entity_id;
	      
	      $course_wrapper = entity_metadata_wrapper('node', $entity_id);
	      $region_field = $course_wrapper->field_global_region->value();
	      if (in_array($current_location, $region_field)) {
		      $items_course_nids[] = $entity_id;      
	      }
	    }
	    
	    $output_courses = views_embed_view('courses_per_subject', 'block_1', implode(',', $items_course_nids));
	    
	    if (count($items_course_nids)) {
		    $items[] = array('data' => "<div class='division'><h3>" . $division_title . "</h3><div class='division-description'>" . $division_description . "</div></div>" . $output_courses,
	                     'class' => array('subject-division', 'clearfix'));
	    }
	  }
	} else {
	  // subjects containing no divisions
	  $output_courses = "";
	  $items_course_nids = array();
	  // get basic info for this subject
    $subject_wrapper = entity_metadata_wrapper('taxonomy_term', $tid);
    $subject_name = $subject_wrapper->name->value();
    $subject_description = $subject_wrapper->description->value();
    
    $result = db_query("SELECT DISTINCT * FROM {node} n, {field_data_field_course_catalog_subject} s, {field_data_field_global_order} o
      WHERE n.nid = o.entity_id
      AND n.type = 'course'
      AND n.nid = s.entity_id
      AND s.field_course_catalog_subject_tid=:subject_tid
      ORDER BY o.field_global_order_value ASC;",
      array(':subject_tid' => $tid));

    foreach ($result as $row) {
      $course_nid = $row->nid;
      $course_wrapper = entity_metadata_wrapper('node', $course_nid);
      $region_field = $course_wrapper->field_global_region->value();
      $current_location = $_SESSION['user_location']['continent_code'];
      if (in_array($current_location, $region_field)) {
        $items_course_nids[] = $course_nid;
      }
    }

    $output_courses = views_embed_view('courses_per_subject', 'block_1', implode(',', $items_course_nids));
	    
    if (count($items_course_nids)) {
		    $items[] = array('data' => "<div class='division'><h3>" . $subject_name . "</h3><div class='division-description'>" . $subject_description . "</div></div>" . $output_courses,
	                     'class' => array('subject-division', 'clearfix'));
    }
   
	}
  
  $block['#markup'] = theme('item_list', array('items' => $items, 'attributes' => array('class' => 'subject-divisions clearfix'))) . '<a class="to-top to-top-block" href="#">Top&nbsp;<i class="icon-arrow-up"></i></a>';
  
  return $block;
}


/**
 * Helper function for rendering Course Page header block
 */
function _hc_blocks_block_course_header_render() {
  $block = array();
  
  if (is_numeric(arg(1))) {
    $nid = arg(1);
    $node_wrapper = entity_metadata_wrapper('node', $nid);
    $course_header_field = $node_wrapper->field_course_header->value();
    if ($course_header_field) {
	    $course_header_wrapper = entity_metadata_wrapper('field_collection_item', $course_header_field->item_id);
	    
	    $course_header_title = $course_header_wrapper->field_course_header_title->value();
	    $course_header_text = $course_header_wrapper->field_course_header_text->value();
	    
	    $course_header_visual = $course_header_wrapper->field_course_header_visual->value();
	    $course_header_visual_path = file_create_url($course_header_visual['uri']);
	    $course_header_visual_image = theme('image', array('path' => $course_header_visual_path));
	    
	    $course_header_information_text = $course_header_wrapper->field_course_header_information->value();
	    $course_header_information_text_formatted = $course_header_information_text['value'];
	    
	    $output = "<div class='image'>" . $course_header_visual_image . "</div>"
	      . "<div class='text-top'>"
	      . "<div class='title'>" . $course_header_title . "</div>"
	      . "<div class='description'>" . $course_header_text . "</div>"
	      . "</div>"
	      . "<div class='text-bottom'>"
	      . "<div class='title'>" . t('Key Information:') . "</div>"
	      . "<div class='description'>" . $course_header_information_text_formatted . "</div>"
	      . "</div>";
    } else {
      $output = "NO HEADER AVAILABLE";
    }

    $block['#markup'] = $output;

  }
  return $block;
}

/**
 * Helper function for rendering public course dates block title 
 */
function _hc_blocks_block_course_public_dates_render_title() {

  $title = "Public Course Dates";

  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $nid = arg(1);
    $node = node_load($nid);
    $node_title = $node->title;
    $title = t('Public Course Dates for @title', array('@title' => $node_title));
  }

  return $title;
}


/**
 * Helper function for rendering public course dates block
 */
function _hc_blocks_block_course_public_dates_render() {

  $output = "";

  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $nid = arg(1);
    $node_wrapper = entity_metadata_wrapper('node', $nid);
    $node_title = $node_wrapper->title->value();
    $public_course_field = $node_wrapper->field_course_public_courses->value();
    if (is_array($public_course_field) && count($public_course_field)) {
      $product_pids = array();
      foreach ($public_course_field as $public_course) {
        $product_pids[] = $public_course->product_id;
      }
      if (count($product_pids)) {
        $output .= "<div class='header clearfix'><div class='left'>Course</div><div class='center'>" . t('Upcoming Public Dates') . "</div><div class='right'>Book</div></div>";
        $output .= "<div class='title clearfix'>" . $node_title . "</div>";
      
        $output .= views_embed_view('public_courses_temp', 'block', implode(',', $product_pids));
        return $output;
      }
    }
  } else {
    return;
  }
}


/**
 * Helper function for rendering Course Testimonials block
 */
function _hc_blocks_block_course_testimonials_render() {

  if (is_numeric(arg(1))) {
    $testimonial_nids = array();
    $nid = arg(1);
    $result = db_query("SELECT entity_id FROM {field_revision_field_testimonial_course_ref} WHERE field_testimonial_course_ref_nid=:course_nid", array(':course_nid' => $nid));
    foreach ($result as $row) {
      $testimonial_nids[] = $row->entity_id;
    }
  }

  $output = views_embed_view('testimonials', 'block', implode(',', $testimonial_nids));

  return $output;
}


/**
 * Helper function for rendering Team Page Header block
 */
function _hc_blocks_block_team_header_render() {
  $block = array();
  
  if (is_numeric(arg(1))) {
    $nid = arg(1);
    $node_wrapper = entity_metadata_wrapper('node', $nid);
    $team_header_field = $node_wrapper->field_team_header->value();
    if ($team_header_field) {
	    $team_header_wrapper = entity_metadata_wrapper('field_collection_item', $team_header_field->item_id);
	    
	    $team_header_title = $team_header_wrapper->field_team_header_title->value();
	    $team_header_text = $team_header_wrapper->field_team_header_text->value();
	    
	    $team_header_visual = $team_header_wrapper->field_team_header_visual->value();
      $team_header_visual_path = image_style_url('subject_header_default', $team_header_visual['uri']);
	    
//	    $team_header_visual_path = file_create_url($team_header_visual['uri']);
	    $team_header_visual_image = theme('image', array('path' => $team_header_visual_path));
	    
	    $output = "<div class='image'>" . $team_header_visual_image . "</div>"
	      . "<div class='text'>"
	      . "<div class='title'>" . $team_header_title . "</div>"
	      . "<div class='description'>" . $team_header_text . "</div>"
	      . "</div>";
    } else {
      $output = "NO HEADER AVAILABLE";
    }

    $block['#markup'] = $output;

  }
  return $block;
}


/**
 * Helper function for rendering Trainer Testimonials block
 */
function _hc_blocks_block_trainer_testimonials_render() {

  if (is_numeric(arg(1))) {
    $testimonial_nids = array();
    $nid = arg(1);
    $result = db_query("SELECT entity_id FROM {field_revision_field_testimonial_team_ref} WHERE field_testimonial_team_ref_nid=:trainer_nid", array(':trainer_nid' => $nid));
    foreach ($result as $row) {
      $testimonial_nids[] = $row->entity_id;
    }
  }

  $output = views_embed_view('testimonials', 'block', implode(',', $testimonial_nids));

  return $output;
}


/**
 * Helper function for rendering book a course page navigation
 */
function _hc_blocks_block_book_a_course_navigation_render() {

  $catalog = taxonomy_get_tree(3);
  
  // get user_location
  $continent_code = $_SESSION['user_location']['continent_code'];
  
  if (is_array($catalog) && count($catalog) > 0) {
    $items = array();
    $items[] = array('data' => '<p class="title">' . t('Which courses<br />are you looking for?') . '</p>');

    foreach ($catalog as $subject) {
      $subject_wrapper = entity_metadata_wrapper('taxonomy_term', $subject->tid);
      $subject_title = $subject_wrapper->name->value();
      $subject_tid = $subject->tid;
      $subject_region = $subject_wrapper->field_global_region->value();
      if (is_array($subject_region)) {
        foreach ($subject_region as $region) {
          if ($region == $continent_code) {
            $items[] = array('data' => "<a href='#'>" . $subject_title . "</a>", 'data-naventityid' => $subject_tid);
          }
        }
      }
    }
  }

  $output = theme('item_list', array('items' => $items, 'attributes' => array('class' => array('clearfix'))));
  
  return $output;
}


/**
 * Helper function for rendering page title block
 */
function _hc_blocks_block_page_title_render() {

  $page_title = drupal_get_title();

/*
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $node = node_load(arg(1));
    $page_title = $node->title;
  }
*/
  
  return $page_title;
}